-- Repro Bovine v1.7.0 - préparation Web Push
-- À exécuter une seule fois dans Supabase > SQL Editor.

create extension if not exists pg_cron;
create extension if not exists pg_net;
create extension if not exists vault;

alter table public.app_settings
  add column if not exists notif_enabled boolean not null default false,
  add column if not exists heat_watch_start_days integer not null default 18,
  add column if not exists postpartum_warn_days integer not null default 45,
  add column if not exists postpartum_late_days integer not null default 60;

-- La table existait déjà dans le premier script Supabase, mais ces lignes rendent
-- le script compatible si elle n'avait pas encore été créée.
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text,
  auth_key text,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

alter table public.push_subscriptions enable row level security;
drop policy if exists "users manage own push" on public.push_subscriptions;
create policy "users manage own push"
on public.push_subscriptions for all
to authenticated
using (user_id = auth.uid() and public.is_household_member(household_id))
with check (user_id = auth.uid() and public.is_household_member(household_id));

create table if not exists public.notification_dispatch_log (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  dispatch_date date not null,
  sent_at timestamptz not null default now(),
  alert_count integer not null default 0,
  device_count integer not null default 0,
  unique(household_id, dispatch_date)
);

alter table public.notification_dispatch_log enable row level security;
-- Pas de policy utilisateur : seule la fonction serveur (service role) y accède.

-- Valeurs utilisées par le Cron officiel Supabase.
select vault.create_secret('https://uuyiazyofyyuxwiolizr.supabase.co', 'repro_project_url')
where not exists (select 1 from vault.decrypted_secrets where name='repro_project_url');
select vault.create_secret('sb_publishable_FtQAhsVfoPbyG1hD3lT1VQ_LhgiW8Hl', 'repro_publishable_key')
where not exists (select 1 from vault.decrypted_secrets where name='repro_publishable_key');

-- Le Cron sera activé APRÈS création/déploiement de l'Edge Function.
